name: Feature Request
description: Suggest an idea for this project.
body:
  - type: markdown
    attributes:
      value: |
        Please check out the [FAQ's](https://ibm.github.io/Technology-Sandbox-Support/)!, Before opening a new issue please search existing [issues](https://github.com/IBM/Developer-Playground-Support/issues)!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: question-area
    attributes:
      label: A clear and concise description of what you want to happen.
      description: To make it easier for us to help you, please include as much useful information as possible.
    validations:
      required: true