name: Feedback
description: Your feedback is highly appreciated and will help us to improve our ability to serve you and other users of our application.
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to provide the feedback!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: input
    id: asset-name
    attributes:
      label: Asset Name
      description: Is feedback related to any particular asset? If so, please provide the Asset name or link
      placeholder: ex. Agro Smart assistant
    validations:
      required: false
  - type: textarea
    id: feedback-area
    attributes:
      label: Provide the feedback here
      description: A clear and concise description
    validations:
      required: true