name: Questions \U0001F914
description: Usage question or discussion about IBM Developer Technology Sandbox. 
body:
  - type: markdown
    attributes:
      value: |
        Please check out the [FAQ's](https://ibm.github.io/Technology-Sandbox-Support/)!, Before opening a new issue please search existing [issues](https://github.com/IBM/Developer-Playground-Support/issues)!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: input
    id: asset-name
    attributes:
      label: Asset Name
      description: Is feedback related to any particular asset? If so, please provide the Asset name or link
      placeholder: ex. Agro Smart assistant
    validations:
      required: false
  - type: textarea
    id: question-area
    attributes:
      label: Post your question here
      description: To make it easier for us to help you, please include as much useful information as possible.
    validations:
      required: true